export const TUTORIAL_SECTIONS = [
  'basicOverview',
  'board',
  'tree',
  'saveLoad',
  'help',
];

export const TUTORIAL_EXAMPLE_SAVE_NAME = 'example_Tutorial';

export const MH_TARGET_SLOTS = [
  { x: 22, y: 10, w: 2, h: 2 },
  { x: 22, y: 12, w: 2, h: 2 },
  { x: 22, y: 14, w: 2, h: 2 },
];

export const CHURCH_TARGET_SLOTS = [
  { x: 8, y: 4, w: 3, h: 3 },
  { x: 8, y: 7, w: 3, h: 3 },
  { x: 8, y: 10, w: 3, h: 3 },
];

export const TUTORIAL_STEPS = [
  {
    id: 'overview-all',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewAllTitle',
    bodyKey: 'tutorialStepOverviewAllBody',
    highlightZones: [
    ],
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-board',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewBoardTitle',
    bodyKey: 'tutorialStepOverviewBoardBody',
    highlight: 'board',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-board-toolbar',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewBoardToolbarTitle',
    bodyKey: 'tutorialStepOverviewBoardToolbarBody',
    highlight: 'mini-toolbar',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-tree',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewTreeTitle',
    bodyKey: 'tutorialStepOverviewTreeBody',
    highlight: 'tree',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-tree-toolbar',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewTreeToolbarTitle',
    bodyKey: 'tutorialStepOverviewTreeToolbarBody',
    highlight: 'tree-toolbar',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-topbar-stats',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewTopbarStatsTitle',
    bodyKey: 'tutorialStepOverviewTopbarStatsBody',
    highlight: 'topbar-stats',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-topbar-steps',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewTopbarStepsTitle',
    bodyKey: 'tutorialStepOverviewTopbarStepsBody',
    highlight: 'topbar-steps',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-topbar-buttons',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewTopbarButtonsTitle',
    bodyKey: 'tutorialStepOverviewTopbarButtonsBody',
    highlight: 'topbar-buttons',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'overview-notes',
    section: 'basicOverview',
    titleKey: 'tutorialStepOverviewNotesTitle',
    bodyKey: 'tutorialStepOverviewNotesBody',
    highlight: 'notes-log',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },

  {
    id: 'board-open-shop',
    section: 'board',
    titleKey: 'tutorialStepBoardOpenShopTitle',
    bodyKey: 'tutorialStepBoardOpenShopBody',
    highlight: 'shop-btn',
    advanceOn: 'action',
    actionType: 'shop-opened',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-select-mh',
    section: 'board',
    titleKey: 'tutorialStepBoardSelectMhTitle',
    bodyKey: 'tutorialStepBoardSelectMhBody',
    highlightZones: ['mh-card', 'shop-panel'],
    advanceOn: 'action',
    actionType: 'building-selected',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-place-mh-sequence',
    section: 'board',
    titleKey: 'tutorialStepBoardPlaceMhTitle',
    bodyKey: 'tutorialStepBoardPlaceMhBody',
    dynamicMode: 'mh-placement',
    advanceOn: 'action',
    actionType: 'board-mh-complete',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-happiness-intro',
    section: 'board',
    titleKey: 'tutorialStepBoardHappinessTitle',
    bodyKey: 'tutorialStepBoardHappinessBody',
    highlightZones: ['happiness-current', 'happiness-tiers'],
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-open-shop-church',
    section: 'board',
    titleKey: 'tutorialStepBoardOpenShopChurchTitle',
    bodyKey: 'tutorialStepBoardOpenShopChurchBody',
    highlight: 'shop-btn',
    advanceOn: 'action',
    actionType: 'shop-opened',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-select-culture-tab',
    section: 'board',
    titleKey: 'tutorialStepBoardSelectCultureTabTitle',
    bodyKey: 'tutorialStepBoardSelectCultureTabBody',
    highlightZones: ['shop-tab-culture', 'shop-panel'],
    advanceOn: 'action',
    actionType: 'shopCategorySelected',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-select-church',
    section: 'board',
    titleKey: 'tutorialStepBoardSelectChurchTitle',
    bodyKey: 'tutorialStepBoardSelectChurchBody',
    highlightZones: ['church-card', 'shop-panel'],
    advanceOn: 'action',
    actionType: 'building-selected',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-place-church-sequence',
    section: 'board',
    titleKey: 'tutorialStepBoardPlaceChurchTitle',
    bodyKey: 'tutorialStepBoardPlaceChurchBody',
    dynamicMode: 'church-placement',
    advanceOn: 'action',
    actionType: 'board-church-complete',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'board-log-intro',
    section: 'board',
    titleKey: 'tutorialStepBoardLogTitle',
    bodyKey: 'tutorialStepBoardLogBody',
    highlight: 'notes-log',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-finish-productions',
    section: 'board',
    titleKey: 'tutorialStepBoardFinishTitle',
    bodyKey: 'tutorialStepBoardFinishBody',
    highlight: 'finish-btn',
    advanceOn: 'action',
    actionType: 'finishProductions',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-finish-time-info',
    section: 'board',
    titleKey: 'tutorialStepBoardFinishTimeInfoTitle',
    bodyKey: 'tutorialStepBoardFinishTimeInfoBody',
    highlight: 'topbar-steps',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-harvest-first-mh',
    section: 'board',
    titleKey: 'tutorialStepBoardHarvestFirstTitle',
    bodyKey: 'tutorialStepBoardHarvestFirstBody',
    dynamicMode: 'mh-first-harvest',
    advanceOn: 'action',
    actionType: 'harvest',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-harvest-all',
    section: 'board',
    titleKey: 'tutorialStepBoardHarvestAllTitle',
    bodyKey: 'tutorialStepBoardHarvestAllBody',
    highlight: 'harvest-btn',
    advanceOn: 'action',
    actionType: 'harvestAll',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'board-tools-overview',
    section: 'board',
    titleKey: 'tutorialStepBoardToolsTitle',
    bodyKey: 'tutorialStepBoardToolsBody',
    highlight: 'board-tools-group',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },

  {
    id: 'tree-intro',
    section: 'tree',
    titleKey: 'tutorialStepTreeIntroTitle',
    bodyKey: 'tutorialStepTreeIntroBody',
    highlight: 'tree',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-node-focus-info',
    section: 'tree',
    titleKey: 'tutorialStepTreeNodeFocusTitle',
    bodyKey: 'tutorialStepTreeNodeFocusBody',
    highlight: 'tree-node-focus-btn',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-zoom-out',
    section: 'tree',
    titleKey: 'tutorialStepTreeZoomOutTitle',
    bodyKey: 'tutorialStepTreeZoomOutBody',
    highlight: 'tree-zoom-slider',
    advanceOn: 'action',
    actionType: 'treeZoomOut',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-go-start',
    section: 'tree',
    titleKey: 'tutorialStepTreeGoStartTitle',
    bodyKey: 'tutorialStepTreeGoStartBody',
    dynamicMode: 'tree-root-node',
    advanceOn: 'action',
    actionType: 'jumpHistoryStart',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-open-shop-gutshaus',
    section: 'tree',
    titleKey: 'tutorialStepTreeOpenShopGutshausTitle',
    bodyKey: 'tutorialStepTreeOpenShopGutshausBody',
    highlight: 'shop-btn',
    advanceOn: 'action',
    actionType: 'shop-opened',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'tree-select-gutshaus',
    section: 'tree',
    titleKey: 'tutorialStepTreeSelectGutshausTitle',
    bodyKey: 'tutorialStepTreeSelectGutshausBody',
    highlightZones: ['gutshaus-card', 'shop-panel'],
    advanceOn: 'action',
    actionType: 'building-selected',
    allowedPopups: ['shop'],
    disabledZones: [],
  },
  {
    id: 'tree-place-gutshaus',
    section: 'tree',
    titleKey: 'tutorialStepTreePlaceGutshausTitle',
    bodyKey: 'tutorialStepTreePlaceGutshausBody',
    dynamicMode: 'gutshaus-first-slot',
    advanceOn: 'action',
    actionType: 'build',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-copy-first-to-second',
    section: 'tree',
    titleKey: 'tutorialStepTreeCopyFirstToSecondTitle',
    bodyKey: 'tutorialStepTreeCopyFirstToSecondBody',
    highlight: 'tree',
    showArrow: true,
    dynamicArrowMode: 'root-first-to-second',
    advanceOn: 'action',
    actionType: 'copyBranchFirstToSecond',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-open-fix',
    section: 'tree',
    titleKey: 'tutorialStepTreeOpenFixTitle',
    bodyKey: 'tutorialStepTreeOpenFixBody',
    highlight: 'tree-fix-btn',
    advanceOn: 'action',
    actionType: 'treeFixOpened',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-fix-popup',
    section: 'tree',
    titleKey: 'tutorialStepTreeFixPopupTitle',
    bodyKey: 'tutorialStepTreeFixPopupBody',
    highlight: 'tree-fix-popup',
    advanceOn: 'action',
    actionType: 'treeFixPopupClosed',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-inspect-second-branch',
    section: 'tree',
    titleKey: 'tutorialStepTreeInspectSecondBranchTitle',
    bodyKey: 'tutorialStepTreeInspectSecondBranchBody',
    dynamicMode: 'tree-root-second-branch-tail',
    advanceOn: 'action',
    actionType: 'inspectSecondBranchTail',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-branch-effects-info',
    section: 'tree',
    titleKey: 'tutorialStepTreeBranchEffectsTitle',
    bodyKey: 'tutorialStepTreeBranchEffectsBody',
    highlight: 'topbar-stats',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-make-main',
    section: 'tree',
    titleKey: 'tutorialStepTreeMainBranchTitle',
    bodyKey: 'tutorialStepTreeMainBranchBody',
    highlight: 'tree-toolbar-main',
    advanceOn: 'action',
    actionType: 'makeTopBranch',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-collapse-horizontal',
    section: 'tree',
    titleKey: 'tutorialStepTreeCollapseBtnTitle',
    bodyKey: 'tutorialStepTreeCollapseBtnBody',
    highlight: 'tree-toolbar-collapse',
    advanceOn: 'action',
    actionType: 'treeToggleHorizontal',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-collapse-focus',
    section: 'tree',
    titleKey: 'tutorialStepTreeFocusBtnTitle',
    bodyKey: 'tutorialStepTreeFocusBtnBody',
    highlight: 'tree-toolbar-focus',
    advanceOn: 'action',
    actionType: 'treeToggleFocus',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-hidden-branch-root',
    section: 'tree',
    titleKey: 'tutorialStepTreeHiddenBranchRootTitle',
    bodyKey: 'tutorialStepTreeHiddenBranchRootBody',
    dynamicMode: 'tree-root-node',
    advanceOn: 'action',
    actionType: 'jumpHistoryStart',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-hidden-branch-select-second',
    section: 'tree',
    titleKey: 'tutorialStepTreeHiddenBranchSelectTitle',
    bodyKey: 'tutorialStepTreeHiddenBranchSelectBody',
    dynamicMode: 'tree-root-second-child-node',
    advanceOn: 'action',
    actionType: 'jumpHistorySecondRootChild',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-hidden-branch-info',
    section: 'tree',
    titleKey: 'tutorialStepTreeHiddenBranchInfoTitle',
    bodyKey: 'tutorialStepTreeHiddenBranchInfoBody',
    highlight: 'tree',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-delete-intro',
    section: 'tree',
    titleKey: 'tutorialStepTreeDeleteIntroTitle',
    bodyKey: 'tutorialStepTreeDeleteIntroBody',
    highlight: 'tree-toolbar-delete',
    advanceOn: 'action',
    actionType: 'treeDeleteModeChanged',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-delete-second-branch-subtree',
    section: 'tree',
    titleKey: 'tutorialStepTreeDeleteSecondBranchTitle',
    bodyKey: 'tutorialStepTreeDeleteSecondBranchBody',
    dynamicMode: 'tree-root-second-child-edge',
    advanceOn: 'action',
    actionType: 'treeDeleteSecondBranchSubtree',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'tree-delete-warning-info',
    section: 'tree',
    titleKey: 'tutorialStepTreeDeleteWarningTitle',
    bodyKey: 'tutorialStepTreeDeleteWarningBody',
    highlight: 'tree',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },

  {
    id: 'save-load-save',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadSaveTitle',
    bodyKey: 'tutorialStepSaveLoadSaveBody',
    highlight: 'save-controls',
    advanceOn: 'action',
    actionType: 'save',
    allowedPopups: [],
    disabledZones: [],
  },
  {
    id: 'save-load-open-menu',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadOpenMenuTitle',
    bodyKey: 'tutorialStepSaveLoadOpenMenuBody',
    highlight: 'load-btn',
    advanceOn: 'action',
    actionType: 'loadMenuOpened',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-btn-load',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadBtnLoadTitle',
    bodyKey: 'tutorialStepSaveLoadBtnLoadBody',
    highlight: 'load-main-btn',
    advanceOn: 'click',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-btn-rename',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadBtnRenameTitle',
    bodyKey: 'tutorialStepSaveLoadBtnRenameBody',
    highlight: 'load-rename-btn',
    advanceOn: 'click',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-btn-export',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadBtnExportTitle',
    bodyKey: 'tutorialStepSaveLoadBtnExportBody',
    highlight: 'load-export-btn',
    advanceOn: 'click',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-btn-delete',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadBtnDeleteTitle',
    bodyKey: 'tutorialStepSaveLoadBtnDeleteBody',
    highlight: 'load-delete-btn',
    advanceOn: 'click',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-load-example',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadLoadExampleTitle',
    bodyKey: 'tutorialStepSaveLoadLoadExampleBody',
    highlight: 'load-main-btn',
    advanceOn: 'action',
    actionType: 'loadExampleSave',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-close-menu',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadCloseMenuTitle',
    bodyKey: 'tutorialStepSaveLoadCloseMenuBody',
    highlight: 'load-modal-close',
    advanceOn: 'action',
    actionType: 'loadMenuClosed',
    allowedPopups: ['loadSavesModal'],
    disabledZones: [],
  },
  {
    id: 'save-load-step-jump-info',
    section: 'saveLoad',
    titleKey: 'tutorialStepSaveLoadStepJumpTitle',
    bodyKey: 'tutorialStepSaveLoadStepJumpBody',
    highlight: 'topbar-steps',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },

  {
    id: 'help',
    section: 'help',
    titleKey: 'tutorialStepHelpTitle',
    bodyKey: 'tutorialStepHelpBody',
    highlight: 'help-btn',
    advanceOn: 'action',
    actionType: 'helpOpened',
    allowedPopups: ['helpModal'],
    disabledZones: [],
  },
  {
    id: 'complete',
    section: 'help',
    titleKey: 'tutorialStepCompleteTitle',
    bodyKey: 'tutorialStepCompleteBody',
    highlight: 'board',
    advanceOn: 'click',
    allowedPopups: [],
    disabledZones: [],
  },
];
