// Builds the public controller interface to keep useGameController small.
export const buildControllerReturn = ({
  state,
  statsApi,
  viewApi,
  regionApi,
  selectionApi,
  modeApi,
  productionApi,
  smartHarvestApi,
  smartInvestApi,
  moneyOptimizerApi,
  supplyOptimizerApi,
  resetOptimizer,
  resetOptimizerToken,
  notesApi,
  economyApi,
  adminEditors,
  adminApi,
  checkpointTools,
  snapshotApi,
  historyApi,
  isCellUnlocked,
  saveTransferApi,
  placementApi,
}) => ({
  resources: state.resources,
  layout: state.layout,
  selectedIds: state.selectedIds,
  libraryMap: state.libraryMap,
  shortIdMap: state.shortIdMap,
  categories: state.categories,
  categoryColors: state.categoryColors,
  selectedCategory: state.selectedCategory,
  setSelectedCategory: state.setSelectedCategory,
  selectedBuildingId: state.selectedBuildingId,
  setSelectedBuildingId: state.setSelectedBuildingId,
  autoSelectNew: state.autoSelectNew,
  setAutoSelectNew: state.setAutoSelectNew,
  unlockedRegions: state.unlockedRegions,
  goodsUnlocks: state.goodsUnlocks,
  shardUnlocks: state.shardUnlocks,
  setGoodsUnlocks: regionApi.handleSetGoodsUnlocks,
  setShardUnlocks: regionApi.handleSetShardUnlocks,
  goodsModal: state.goodsModal,
  setGoodsModal: state.setGoodsModal,
  unitModal: state.unitModal,
  setUnitModal: state.setUnitModal,
  fastBuyModal: state.fastBuyModal,
  fastBuyTarget: state.fastBuyTarget,
  unlockChoice: state.unlockChoice,
  unlockGoodSelect: state.unlockGoodSelect,
  viewMode: state.viewMode,
  setViewMode: state.setViewMode,
  boardScale: state.boardScale,
  setBoardScale: state.setBoardScale,
  status: state.status,
  notes: state.notes,
  setNotes: state.setNotes,
  handleChangeNotes: notesApi.handleChangeNotes,
  toolbarPosition: state.toolbarPosition,
  setToolbarPosition: state.setToolbarPosition,
  warnDeleteSingleAction: state.warnDeleteSingleAction,
  setWarnDeleteSingleAction: state.setWarnDeleteSingleAction,
  warnDeleteSubtree: state.warnDeleteSubtree,
  setWarnDeleteSubtree: state.setWarnDeleteSubtree,
  carried: state.carried,
  readyMap: state.readyMap,
  buildLocks: state.buildLocks,
  hoverCell: state.hoverCell,
  setHoverCell: state.setHoverCell,
  moveMode: state.moveMode,
  sellMode: state.sellMode,
  refundMode: state.refundMode,
  boostMode: state.boostMode,
  saves: snapshotApi.saves,
  savesLoaded: snapshotApi.savesLoaded,
  setAllSaves: snapshotApi.setAllSaves,
  visibleSaves: snapshotApi.visibleSaves,
  snapshots: snapshotApi.snapshots,
  loadName: snapshotApi.loadName,
  setLoadName: snapshotApi.setLoadName,
  harvestModal: state.harvestModal,
  smartHarvestModal: state.smartHarvestModal,
  smartInvestModal: state.smartInvestModal,
  smartInvestResults: state.smartInvestResults,
  smartInvestRunning: state.smartInvestRunning,
  optimizerModalOpen: supplyOptimizerApi.modalOpen,
  supplyOptimizerState: supplyOptimizerApi.optimizerState,
  moneyOptimizerState: moneyOptimizerApi.optimizerState,
  moneyOptimizerRunning: moneyOptimizerApi.optimizerState?.running ?? false,
  optimizerRunning:
    (supplyOptimizerApi.optimizerState?.running ?? false) ||
    (moneyOptimizerApi.optimizerState?.running ?? false),
  stats: statsApi.stats,
  happyInfo: statsApi.happyInfo,
  previewOrigin: viewApi.previewOrigin,
  viewRotation: viewApi.viewRotation,
  boardTransform: viewApi.boardTransform,
  regionTransform: viewApi.regionTransform,
  toolbarOffsetPx: viewApi.toolbarOffsetPx,
  statusOffsetPx: viewApi.statusOffsetPx,
  boardTransformClass: viewApi.boardTransformClass,
  cellSizePx: viewApi.cellSizePx,
  rotatedWidthPx: viewApi.rotatedWidthPx,
  rotatedHeightPx: viewApi.rotatedHeightPx,
  viewWidth: viewApi.viewWidth,
  viewHeight: viewApi.viewHeight,
  viewColStart: viewApi.viewColStart,
  viewRowStart: viewApi.viewRowStart,
  setContainerHeight: state.setContainerHeight,
  setContainerWidth: state.setContainerWidth,
  currentGoodsCost: regionApi.currentGoodsCost,
  currentShardCost: regionApi.currentShardCost,
  neighborUnlocked: regionApi.neighborUnlocked,
  hasAnyGoodsProducer: regionApi.hasAnyGoodsProducer,
  hasAnyGoodsEnough: regionApi.hasAnyGoodsEnough,
  canAnyUnlock: regionApi.canAnyUnlock,
  handleCellClick: placementApi.handleCellClick,
  onCancelAction: placementApi.onCancelAction,
  handleUnlockRegion: regionApi.handleUnlockRegion,
  handleDebugUnlockRegion: regionApi.handleDebugUnlockRegion,
  handleDebugLockRegion: regionApi.handleDebugLockRegion,
  handleAdminLockRegion: regionApi.handleAdminLockRegion,
  toggleMove: modeApi.toggleMove,
  toggleSell: modeApi.toggleSell,
  toggleRefund: modeApi.toggleRefund,
  toggleBoost: modeApi.toggleBoost,
  toggleSelectId: selectionApi.toggleSelectId,
  clearSelection: selectionApi.clearSelection,
  handleSelectBuilding: modeApi.handleSelectBuilding,
  finishProductions: productionApi.finishProductions,
  harvestAll: productionApi.harvestAll,
  harvestPartialOnly: productionApi.harvestPartialOnly,
  handleSmartHarvest: smartHarvestApi.handleSmartHarvest,
  handleSmartInvest: smartInvestApi.handleSmartInvest,
  openSmartInvestResults: smartInvestApi.openSmartInvestResults,
  continueSmartInvest: smartInvestApi.continueSmartInvest,
  closeSmartInvestModal: smartInvestApi.closeSmartInvestModal,
  applySmartInvestResult: smartInvestApi.applySmartInvestResult,
  openOptimizer: supplyOptimizerApi.openSupplyOptimizer,
  closeOptimizer: supplyOptimizerApi.closeSupplyOptimizer,
  stepSupplyOptimizerOnce: supplyOptimizerApi.stepOnce,
  stepSupplyOptimizerFew: supplyOptimizerApi.stepFew,
  finishSupplyOptimizer: supplyOptimizerApi.finish,
  stepMoneyOptimizerOnce: moneyOptimizerApi.stepOnce,
  stepMoneyOptimizerFew: moneyOptimizerApi.stepFew,
  finishMoneyOptimizer: moneyOptimizerApi.finish,
  resetOptimizer,
  resetOptimizerToken,
  harvestFullForPdf: productionApi.harvestFullForPdf,
  confirmHarvest: productionApi.confirmHarvest,
  cancelHarvest: productionApi.cancelHarvest,
  confirmSmartHarvest: smartHarvestApi.confirmSmartHarvest,
  handleSaveState: snapshotApi.handleSaveState,
  handleTakeSnapshot: snapshotApi.handleTakeSnapshot,
  handleLoadState: snapshotApi.handleLoadState,
  deleteSave: snapshotApi.deleteSave,
  // Compute hasUnsavedChanges: true if tree node count differs from last saved
  hasUnsavedChanges: (() => {
    const loadName = snapshotApi.loadName;
    const lastSavedNodeCount = snapshotApi.lastSavedNodeCount;
    const currentNodeCount = historyApi?.historyTree?.nodes?.size ?? 0;
    if (!loadName) return false; // No savefile loaded
    if (lastSavedNodeCount === null) return false; // Initial state
    return currentNodeCount !== lastSavedNodeCount;
  })(),
  worstModal: state.worstModal,
  openWorstModal: statsApi.openWorstModal,
  setWorstModal: state.setWorstModal,
  exportModal: state.exportModal,
  importModal: state.importModal,
  loadSavesModal: state.loadSavesModal,
  onlineLibraryModal: state.onlineLibraryModal,
  setExportModal: state.setExportModal,
  setImportModal: state.setImportModal,
  setLoadSavesModal: state.setLoadSavesModal,
  setOnlineLibraryModal: state.setOnlineLibraryModal,
  openExportSaves: saveTransferApi.openExportSaves,
  openImportSaves: saveTransferApi.openImportSaves,
  openLoadSavesModal: saveTransferApi.openLoadSavesModal,
  handleExportSelected: saveTransferApi.handleExportSelected,
  handleExportSavefile: saveTransferApi.handleExportSavefile,
  handleUploadSharedSave: saveTransferApi.handleUploadSharedSave,
  handleRenameSavefile: saveTransferApi.handleRenameSavefile,
  handleDeleteSavefile: saveTransferApi.handleDeleteSavefile,
  handleImportSelected: saveTransferApi.handleImportSelected,
  checkpoints: snapshotApi.checkpoints,
  setCheckpointIndex: snapshotApi.setCheckpointIndex,
  timeStep: state.timeStep,
  setTimeStep: state.setTimeStep,
  checkpointIndex: snapshotApi.checkpointIndex,
  addCheckpointPart: snapshotApi.addCheckpointPart,
  currentPart: snapshotApi.currentPart,
  currentPartTotal: snapshotApi.currentPartTotal,
  editUnlocked: snapshotApi.editUnlocked,
  setEditUnlocked: snapshotApi.setEditUnlocked,
  isPast: snapshotApi.isPast,
  editingLocked: snapshotApi.editingLocked,
  canTimeBack: snapshotApi.canTimeBack,
  canTimeForward: snapshotApi.canTimeForward,
  jumpBackTime: snapshotApi.jumpBackTime,
  jumpForwardTime: snapshotApi.jumpForwardTime,
  enableEditFromPast: snapshotApi.enableEditFromPast,
  pastEditModal: state.pastEditModal,
  openPastEditModal: snapshotApi.openPastEditModal,
  closePastEditModal: snapshotApi.closePastEditModal,
  handleCopyAndEnableEdit: snapshotApi.handleCopyAndEnableEdit,
  handleEnableEditFromPast: snapshotApi.handleEnableEditFromPast,
  setFastBuyModal: state.setFastBuyModal,
  setFastBuyTarget: state.setFastBuyTarget,
  setUnlockChoice: state.setUnlockChoice,
  setUnlockGoodSelect: state.setUnlockGoodSelect,
  handleGoodsPurchase: economyApi.handleGoodsPurchase,
  handleUnitPurchase: economyApi.handleUnitPurchase,
  handleFastBuy: economyApi.handleFastBuy,
  resetModes: modeApi.resetModes,
  handleEditResource: adminEditors.handleEditResource,
  handleEditGood: adminEditors.handleEditGood,
  handleEditUnit: adminEditors.handleEditUnit,
  buildSnapshot: snapshotApi.buildSnapshot,
  applySnapshot: snapshotApi.applySnapshot,
  pauseCheckpointTracking: snapshotApi.pauseCheckpointTracking,
  resumeCheckpointTracking: snapshotApi.resumeCheckpointTracking,
  historyIndex: historyApi?.historyIndex ?? 0,
  historyTree: historyApi?.historyTree ?? null,
  computeStateAtNode: historyApi?.computeStateAtNode,
  setHistoryTree: historyApi?.setHistoryTree,
  setSelectedNodeId: historyApi?.setSelectedNodeId,
  historyNodes: historyApi?.historyNodes ?? (() => []),
  branchComparisonHighlight: historyApi?.branchComparisonHighlight ?? null,
  historyInvalidSteps: historyApi?.historyInvalidSteps ?? [],
  historyChecking: historyApi?.historyChecking ?? false,
  jumpToHistory: historyApi?.jumpToHistory,
  makeTopBranch: historyApi?.makeTopBranch,
  copyBranchTo: historyApi?.copyBranchTo,
  loadHistoryTree: historyApi?.loadHistoryTree,
  deleteNode: historyApi?.deleteNode,
  applyLayoutFix: historyApi?.applyLayoutFix,
  isCellUnlocked,
  toggleAutoSelectNew: selectionApi.toggleAutoSelectNew,
  infiniteResources: state.infiniteResources,
  handleToggleInfinite: adminApi.handleToggleInfinite,
  helpModal: state.helpModal,
  setHelpModal: state.setHelpModal,
  editGoodModal: state.editGoodModal,
  setEditGoodModal: state.setEditGoodModal,
  config: state.config,
  userConfig: state.userConfig,
  activeSaveConfig: state.activeSaveConfig,
  setActiveSaveConfig: state.setActiveSaveConfig,
  updateConfig: state.updateConfig,
  replaceConfig: state.replaceConfig,
  applyStartBonusToCheckpoints: checkpointTools.applyStartBonusToCheckpoints,
  applyGoodEdit: adminEditors.applyGoodEdit,
  cancelEditGood: adminEditors.cancelEditGood,
  editResourceModal: state.editResourceModal,
  setEditResourceModal: state.setEditResourceModal,
  applyResourceEdit: adminEditors.applyResourceEdit,
  cancelEditResource: adminEditors.cancelEditResource,
  editUnitModal: state.editUnitModal,
  setEditUnitModal: state.setEditUnitModal,
  applyUnitEdit: adminEditors.applyUnitEdit,
  cancelEditUnit: adminEditors.cancelEditUnit,
  selectedSnapshotName: snapshotApi.selectedSnapshotName,
  setSelectedSnapshotName: snapshotApi.setSelectedSnapshotName,
});
