import { useCallback, useEffect } from "react";
import {
  buildSnapshot as buildSnapshotState,
  applySnapshot as applySnapshotState,
} from "../../state/snapshot";
import { useCheckpoints } from "../useCheckpoints";

// Core snapshot building and checkpoint timeline tracking.
export const useCheckpointManager = ({
  resources,
  layout,
  unlockedRegions,
  goodsUnlocks,
  shardUnlocks,
  readyMap,
  buildLocks,
  moveMode,
  sellMode,
  refundMode,
  boostMode,
  selectedCategory,
  notes,
  timeStep,
  loadName,
  selectedBuildingId,
  selectedIds,
  townhallDef,
  nextIdRef,
  setResources,
  setLayout,
  setUnlockedRegions,
  setGoodsUnlocks,
  setShardUnlocks,
  setReadyMap,
  setBuildLocks,
  setBoostMode,
  setMoveMode,
  setSellMode,
  setRefundMode,
  setSelectedCategory,
  setTimeStep,
  setLoadName,
  setNotes,
  setSelectedIds,
}) => {
  const buildSnapshot = useCallback(
    () =>
      buildSnapshotState({
        resources,
        layout,
        unlockedRegions,
        goodsUnlocks,
        shardUnlocks,
        nextId: nextIdRef.current,
        readyMap,
        buildLocks,
        moveMode,
        sellMode,
        refundMode,
        boostMode,
        selectedCategory,
        notes,
        timeStep,
        loadName,
        selectedBuildingId,
        selectedIds: Array.from(selectedIds ?? []),
      }),
    [
      resources,
      layout,
      unlockedRegions,
      goodsUnlocks,
      shardUnlocks,
      readyMap,
      buildLocks,
      boostMode,
      moveMode,
      sellMode,
      refundMode,
      selectedCategory,
      notes,
      timeStep,
      selectedIds,
      loadName,
      selectedBuildingId,
      nextIdRef,
    ],
  );

  const applySnapshot = useCallback(
    (snapshot) =>
      applySnapshotState(snapshot, {
        setResources,
        setLayout,
        setUnlockedRegions,
        setGoodsUnlocks,
        setShardUnlocks,
        setReadyMap,
        setBuildLocks,
        setBoostMode,
        setMoveMode,
        setSellMode,
        setRefundMode,
        setSelectedCategory,
        setTimeStep,
        setLoadName,
        setNotes,
        setSelectedIds,
        nextIdRef,
        townhallDef,
      }),
    [
      setResources,
      setLayout,
      setUnlockedRegions,
      setGoodsUnlocks,
      setShardUnlocks,
      setReadyMap,
      setBuildLocks,
      setBoostMode,
      setMoveMode,
      setSellMode,
      setRefundMode,
      setSelectedCategory,
      setTimeStep,
      setLoadName,
      setNotes,
      setSelectedIds,
      townhallDef,
      nextIdRef,
    ],
  );

  const {
    checkpoints,
    checkpointIndex,
    setCheckpointIndex,
    editUnlocked,
    setEditUnlocked,
    isPast,
    editingLocked,
    canTimeBack,
    canTimeForward,
    jumpBackTime,
    jumpForwardTime,
    branchFromPast,
    trimFutureCheckpoints,
    applyLoadedCheckpoints,
    updateCheckpoints,
    makeCheckpointsForSave,
    addCheckpointPart,
    currentPart,
    currentPartTotal,
    suppressNextCheckpoint,
    overwriteCheckpointAtIndex,
    enableEditFromPast,
    pauseCheckpointTracking,
    resumeCheckpointTracking,
  } = useCheckpoints({
    buildSnapshot,
    applySnapshot,
    timeStep,
    setTimeStep,
  });

  useEffect(() => {
    if (checkpointIndex === null) return;
    const snap = buildSnapshot();
    overwriteCheckpointAtIndex(snap, checkpointIndex);
  }, [
    checkpointIndex,
    buildSnapshot,
    overwriteCheckpointAtIndex,
    layout,
    resources,
    readyMap,
    buildLocks,
    notes,
    selectedIds,
    selectedBuildingId,
    timeStep,
  ]);

  return {
    buildSnapshot,
    applySnapshot,
    checkpoints,
    checkpointIndex,
    setCheckpointIndex,
    editUnlocked,
    setEditUnlocked,
    isPast,
    editingLocked,
    canTimeBack,
    canTimeForward,
    jumpBackTime,
    jumpForwardTime,
    branchFromPast,
    trimFutureCheckpoints,
    applyLoadedCheckpoints,
    updateCheckpoints,
    makeCheckpointsForSave,
    addCheckpointPart,
    currentPart,
    currentPartTotal,
    suppressNextCheckpoint,
    overwriteCheckpointAtIndex,
    enableEditFromPast,
    pauseCheckpointTracking,
    resumeCheckpointTracking,
  };
};
